services:
  postgres:
    container_name: bank-app
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'dbprod'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'password'
      POSTGRES_DB: 'sample_database'
    ports:
      - "5432:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
